package com.thetatechnolabs.foundation

import androidx.annotation.LayoutRes
import androidx.appcompat.app.AppCompatActivity
import androidx.databinding.DataBindingUtil
import androidx.databinding.ViewDataBinding

abstract class BaseActivity<out T : ViewDataBinding>(
    @LayoutRes private val layoutRes: Int
) : AppCompatActivity() {

    /**
     * A data-binding property will be initialized before being called [onCreate].
     * And inflates using the [layoutRes] as a content view for activities.
     */
    @Bindables
    protected val binding: T by lazy(LazyThreadSafetyMode.NONE) {
        DataBindingUtil.setContentView<T>(this, layoutRes).also {
            it.lifecycleOwner = this
        }
    }

    /**
     * An executable inline binding function that receives a binding receiver in lambda.
     *
     * @param block A lambda block will be executed with the binding receiver.
     * @return T A generic class that extends [ViewDataBinding] and generated by DataBinding on compile time.
     */
    @Bindables
    protected inline fun binding(block: T.() -> Unit): T = binding.apply(block)

    /**
     * Ensures the binding property should be executed before being called onCreate.
     */
    init {
        addOnContextAvailableListener {
            binding.notifyChange()
        }
    }
}